### ISSUE TITLE
getting ERROR results .frd file was not written

### ISSUE THREAD

**Issue by jnschilling** [tavjo/Pycalculix#1]
Hi, 
I am getting an error on jupiter py3.6 , do you have any solution to this ?
![image](https://user-images.githubusercontent.com/13500514/28421161-9a8f3acc-6d64-11e7-8b31-0fd249447fd0.png)

**Comment by WenjinTao** [comment]
Not sure about this. It seems the .frd file was not generated after calling the solver.
Have you tried the 64bit version
